export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS';
export const FILTER_BAR_CHANGE = 'FILTER_BAR_CHANGE';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
